export { default as StepAccountInfo } from './account-info';
export { default as StepAddressInfo } from './address-info';
export { default as StepApplicantPhoto } from './applicant-photo';
export { default as StepAttachmentInfo } from './attachment-info';
export { default as StepBillInfo } from './bill-info';
export { default as ConfirmationTab } from './confirmation-tab';
export { default as StepContactInfo } from './contact-info';
export { default as StepGovernmentInfo } from './government-info';
export { default as StepRequirements } from './requirements';
